### ISSUE TITLE
Import Error - from glm.glm import GLM

### ISSUE THREAD

**Issue by bscully27** [madrury/py-glm#5]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\IPython\core\interactiveshell.py", line 2878, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-d1734a7c0588>", line 1, in <module>
    from glm.glm import GLM
  File "C:\Users\Ben\.p2\pool\plugins\org.python.pydev.core_7.0.3.201811082356\pysrc\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Python27\lib\site-packages\py_glm-0.0.1-py2.7.egg\glm\glm.py", line 104
    def fit(self, X, y=None, formula=None, *,

**Comment by madrury** [comment]
@bscully27 Are you running python 2.7?  This library only works with python 3.x

**Comment by bscully27** [comment]
I just installed on python3 and the import works fine.  Thanks for the help.
